events {
    worker_connections 1024;
}

http {}	

stream {
    upstream pages_nginx {
        server 10.15.0.11:8080 weight=3;
        server 10.15.0.12:8080 max_conns=15 fail_timeout=30s;
        server 10.15.0.13:8080 backup; 
    }

    server { 
    listen 80;
        proxy_pass pages_nginx;
        proxy_timeout 3s;
        proxy_connect_timeout 1s;
    }
}

