events {}
http {
    upstream backend {
        server 10.15.0.11:8080 weight=4;
        server 10.15.0.12:8080;
        server 10.15.0.13:8080 backup;
        }

    upstream api_backend {
        server 10.15.0.14:8080 weight=2;
        server 10.15.0.15:8080;
    }

# HTTP Redirect
server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name 127.0.0.1 app.backend.com;

    ssl_certificate /etc/nginx/ssl/localhost+2.pem;
    ssl_certificate_key /etc/nginx/ssl/localhost+2-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /static/ {
        root /var/www/html;
    }

    location /api/ {
        proxy_pass http://api_backend/;
    }

    location / {
	proxy_pass http://backend;
	
	proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
